instruments:
  keysight-b1500a:
    label: Keysight B1500A Semiconductor Parameter Analyzer
    location: gtiit-china
    type: semiconductor-device-analyzer
    parsing:
      delimiter: ','
      decimal: .
      header_lines_default: 246
      encoding: utf-8
      columns:
        voltage: V1
        current: I2
  keithley-2400:
    label: Keithley 2400 SourceMeter
    location: usth-hanoi
    type: sourcemeter
    parsing:
      delimiter: "\t"
      decimal: .
      header_lines_default: 23
      encoding: utf-8
      columns:
        voltage: Untitled
        current: Untitled 1
        time: Untitled 2
  autolab-usth:
    label: Autolab USTH (CV deposition)
    location: usth-hanoi
    type: potentiostat
    parsing: {}
  horiba-usth:
    label: Horiba LabRAM HR Evolution (USTH)
    location: usth-hanoi
    type: raman-spectrometer
    parsing:
      delimiter: "\t"
      decimal: ','
      header_lines_default: 45
      encoding: latin1
      names:
      - shift
      - intensity
  spectrometer-iop:
    label: "UV-Vis Spectrometer (IOP Hanoi) \u2014 vs-770st"
    location: iop-hanoi
    type: uv-vis-spectrometer
    parsing:
      delimiter: ','
      decimal: .
      header_lines_default: 1
      encoding: latin1
      columns:
        wavelength: Wavelength nm.
        transmittance: T%
